### ISSUE TITLE
Publish to PyPI

### ISSUE THREAD

**Issue by Drasli-Tana** [D3DeFi/certbot-vault#4]
Hello,

what do you think about publishing your plugin to PyPI?

**Comment by D3DeFi** [comment]
Hi, sorry for later response. Not a bad idea at all! :) I will look at it when I have more time. Previously I didn't consider it as I haven't expected at all to stumble upon this repo 😅

**Comment by D3DeFi** [comment]
Ok, why not. Can I help in some way? Do you need any permissions to this repository/etc?

**Comment by D3DeFi** [comment]
Understood, good work though! I will get the secret and add it to the repository in the coming days

What do you think about one of these?
- certbot-installer-vault / certbot-vault-installer
- certbot-plugin-vault

**Comment by D3DeFi** [comment]
https://pypi.org/project/certbot-vault-installer/0.4.1/ ! 🚀 

https://github.com/D3DeFi/certbot-vault/actions/runs/3596705233/jobs/6057670896

Awesome work! thank you for all the help.

**Comment by D3DeFi** [comment]
Fixed by #5
